export * as UserController from '../controllers/UserController.js'
export * as CommentContoller from '../controllers/CommentContoller.js'
export * as DiscuccController from '../controllers/DiscussController.js'
export * as FavouriteController from '../controllers/FavouriteController.js'
export * as PostController from '../controllers/PostController.js'